/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : number,
}
export interface Reservation {
  'id' : bigint,
  'status' : string,
  'date' : string,
  'createdAt' : bigint,
  'time' : string,
  'guestName' : string,
  'email' : string,
  'notes' : string,
  'partySize' : bigint,
  'phone' : string,
}
export interface RestaurantInfo {
  'about' : string,
  'email' : string,
  'address' : string,
  'openingHours' : string,
  'phone' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMenuItem' : ActorMethod<[string, string, number, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createReservation' : ActorMethod<
    [string, string, string, string, string, bigint, string],
    bigint
  >,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'deleteReservation' : ActorMethod<[bigint], undefined>,
  'getAllReservations' : ActorMethod<[], Array<Reservation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRestaurantInfo' : ActorMethod<[], [] | [RestaurantInfo]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAvailableMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'listMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'listMenuItemsByCategory' : ActorMethod<[string], Array<MenuItem>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleMenuItemAvailability' : ActorMethod<[bigint], boolean>,
  'updateMenuItem' : ActorMethod<
    [bigint, string, string, number, string],
    undefined
  >,
  'updateReservationStatus' : ActorMethod<[bigint, string], undefined>,
  'updateRestaurantInfo' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];